# Copyright (C) 2025 - 2026 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: ANSYS MCP SERVER TECHNOLOGY PREVIEW LICENSE AGREEMENT

#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""Example integration tests for MAPDL code generation.

These tests demonstrate how to use the TemplateTest framework to validate
code generated by an LLM using the PYMAPDL_SYSTEM_PROMPT.

To run these tests:
    pytest tests/test_mapdl_code_generation_examples.py -v

Note: These tests require Azure OpenAI credentials via environment variables:
    - AZURE_OPENAI_KEY
    - AZURE_OPENAI_ENDPOINT
    - AZURE_OPENAI_DEPLOYMENT
"""

import os
from unittest.mock import MagicMock

import pytest

from tests.test_mapdl_code_generation import TemplateTest
from tests.test_utils import get_llm_context


@pytest.fixture
def mapdl_fixture():
    """Provide a MAPDL instance for tests.

    Returns real MAPDL if available, mock otherwise.
    """
    use_real_mapdl = os.getenv("USE_REAL_MAPDL", "false").lower() == "true"

    if use_real_mapdl:
        try:
            from ansys.mapdl.core import launch_mapdl

            mapdl = launch_mapdl(start_instance=False)
            yield mapdl
            mapdl.exit()
        except Exception as e:
            pytest.skip(f"Could not launch real MAPDL: {e}")
    else:
        # Use mock MAPDL
        mapdl = MagicMock()
        mapdl.version = "2024 R2"

        # Track entities
        mapdl._entities = {
            "keypoints": {},
            "lines": {},
            "areas": {},
            "volumes": {},
            "nodes": {},
            "elements": {},
        }

        mapdl.jobname = "file"
        mapdl.check_status = "RUNNING"
        mapdl.is_alive = True

        # Entity tracking methods
        def track_keypoint(kp_id, *args, **kwargs):
            mapdl._entities["keypoints"][kp_id] = {
                "id": kp_id,
                "coords": args[:3] if args else (),
            }
            return ""

        def track_line(line_id, *args, **kwargs):
            mapdl._entities["lines"][line_id] = {"id": line_id}
            return ""

        mapdl.k = MagicMock(side_effect=track_keypoint)
        mapdl.l = MagicMock(side_effect=track_line)

        # Mock MAPDL info
        mapdl.information = MagicMock()
        mapdl.information.routine = "PREP7"
        mapdl.information.units = "SI"

        # Dynamic entity counts
        mapdl.geometry = MagicMock()
        mapdl.geometry.n_keypoint = property(
            lambda self: len(mapdl._entities["keypoints"])
        ).__get__(mapdl.geometry, MagicMock)
        mapdl.geometry.n_line = property(lambda self: len(mapdl._entities["lines"])).__get__(
            mapdl.geometry, MagicMock
        )

        # Other mocked methods
        mapdl.prep7 = MagicMock(return_value="")
        mapdl.solu = MagicMock(return_value="")
        mapdl.post1 = MagicMock(return_value="")
        mapdl.et = MagicMock(return_value="")
        mapdl.mp = MagicMock(return_value="")
        mapdl.com = MagicMock(return_value="")
        mapdl.run = MagicMock(return_value="")
        mapdl.exit = MagicMock(return_value="")
        mapdl.clear = MagicMock(return_value="")
        mapdl.parameters = {}
        mapdl.mesh = MagicMock()
        mapdl.mesh.n_node = 0
        mapdl.mesh.n_elem = 0

        yield mapdl


@pytest.fixture
def llm_client():
    """Provide Azure OpenAI client or skip if credentials unavailable."""
    key = os.getenv("AZURE_OPENAI_KEY")
    endpoint = os.getenv("AZURE_OPENAI_ENDPOINT")
    deployment = os.getenv("AZURE_OPENAI_DEPLOYMENT")

    if not all([key, endpoint, deployment]):
        pytest.skip(
            "Azure OpenAI credentials not configured. "
            "Set AZURE_OPENAI_KEY, AZURE_OPENAI_ENDPOINT, AZURE_OPENAI_DEPLOYMENT"
        )

    try:
        from openai import AzureOpenAI

        client = AzureOpenAI(
            api_key=key,
            api_version="2024-02-15-preview",
            azure_endpoint=endpoint,
        )
        return client
    except ImportError:
        pytest.skip("openai library not installed")


@pytest.mark.llm_integration
class TestSimpleKeypoint(TemplateTest):
    """Test generating simple keypoints.

    This test verifies that the LLM can generate code to create keypoints
    at specified coordinates using PyMAPDL.
    """

    query = "Create a keypoint at coordinates (0, 0, 0)"
    num_keypoints = 1
    keypoints = [1]
    commands = ["k"]

    @pytest.fixture(autouse=True)
    def setup_and_execute(self, mapdl_fixture, llm_client):
        """Setup test by querying LLM and executing code."""
        self.setup_class()

        # Query LLM
        mapdl_context = get_llm_context()
        self.run_llm_query(llm_client, mapdl_context)

        # Extract and adapt code
        self.extract_code()
        self.adapt_code()

        # Execute against MAPDL
        self.execute_code(mapdl_fixture)

        # Yield control to test methods (mapdl_fixture available as parameter)
        yield mapdl_fixture


@pytest.mark.llm_integration
class TestTwoKeypoints(TemplateTest):
    """Test generating two keypoints and connecting them.

    This test verifies that the LLM can generate code to create multiple
    keypoints and a line between them.
    """

    query = "Create two keypoints at (0, 0, 0) and (1, 0, 0), then create a line between them"
    num_keypoints = 2
    num_lines = 1
    keypoints = [1, 2]
    lines = [1]
    commands = ["k", "l"]

    @pytest.fixture(autouse=True)
    def setup_and_execute(self, mapdl_fixture, llm_client):
        """Setup test by querying LLM and executing code."""
        self.setup_class()

        # Query LLM
        mapdl_context = get_llm_context()
        self.run_llm_query(llm_client, mapdl_context)

        # Extract and adapt code
        self.extract_code()
        self.adapt_code()

        # Execute against MAPDL
        self.execute_code(mapdl_fixture)

        yield mapdl_fixture
