# Copyright (C) 2025 - 2026 ANSYS, Inc. and/or its affiliates.
# SPDX-License-Identifier: ANSYS MCP SERVER TECHNOLOGY PREVIEW LICENSE AGREEMENT

#
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""Template base class for testing LLM-generated MAPDL code.

This module provides a reusable test framework for validating PyMAPDL/MAPDL code
generated by an LLM when using the PYMAPDL_SYSTEM_PROMPT from the pymapdl-mcp server.

The framework follows the pattern from aali-codegen for comprehensive code validation:
1. Query an LLM with a MAPDL task
2. Extract and adapt the generated code
3. Execute it against a MAPDL instance (real or mock)
4. Validate the results against expected outcomes
"""

import logging
from typing import Any, Callable, Optional

try:
    from genai_test import ContainsWord, Exchange
except ImportError:
    Exchange = None
    ContainsWord = None

import pytest

from tests.test_utils import adapt_code_for_execution, extract_executable_code

logger = logging.getLogger(__name__)


class TemplateTest:
    """Base class for LLM-generated MAPDL code validation tests.

    Subclass this template to define tests. Set class attributes to configure
    what code to generate, what to validate, and how to verify results.

    Attributes
    ----------
    query : str
        The query/task to send to the LLM (e.g., "Create two keypoints at (0,0,0) and (1,1,1)")
    num_nodes : int, optional
        Expected number of nodes after code execution
    num_elements : int, optional
        Expected number of elements after code execution
    num_keypoints : int, optional
        Expected number of keypoints after code execution
    num_lines : int, optional
        Expected number of lines after code execution
    num_areas : int, optional
        Expected number of areas after code execution
    num_volumes : int, optional
        Expected number of volumes after code execution
    keypoints : list[int], optional
        List of expected keypoint IDs (for specific ID validation)
    lines : list[int], optional
        List of expected line IDs
    areas : list[int], optional
        List of expected area IDs
    volumes : list[int], optional
        List of expected volume IDs
    commands : list[str], optional
        List of PyMAPDL commands expected in generated code (e.g., "k", "l")
    words : list[str], optional
        Words expected to appear in the LLM response
    parameters : dict[str, Any], optional
        Parameters expected in the MAPDL model with their values
    functions : list[Callable], optional
        Custom validation functions to run (receive mapdl instance)
    """

    # Test configuration - override in subclasses
    query: str = ""
    num_nodes: Optional[int] = None
    num_elements: Optional[int] = None
    num_keypoints: Optional[int] = None
    num_lines: Optional[int] = None
    num_areas: Optional[int] = None
    num_volumes: Optional[int] = None

    keypoints: list[int] = []
    lines: list[int] = []
    areas: list[int] = []
    volumes: list[int] = []
    nodes: list[int] = []
    elements: list[int] = []

    commands: list[str] = []
    words: list[str] = []
    parameters: dict[str, Any] = {}
    functions: list[Callable] = []

    # Internal state - tracks code and results across test methods
    code: str = ""
    adapted_code: str = ""
    exchange: Optional[Any] = None
    succeed: Optional[bool] = None
    _error: Optional[Exception] = None

    @classmethod
    def setup_class(cls):
        """Reset class state before running tests."""
        cls.code = ""
        cls.adapted_code = ""
        cls.exchange = None
        cls.succeed = None
        cls._error = None

    def run_llm_query(self, llm_client: Any, mapdl_context: tuple[str, list]) -> str:
        """Query the LLM to generate MAPDL code.

        Parameters
        ----------
        llm_client
            Azure OpenAI client or compatible LLM interface
        mapdl_context : tuple[str, list]
            Tuple of (system_prompt, tool_descriptions) from the MCP server

        Returns
        -------
        str
            The LLM response (should contain MAPDL code)
        """
        system_prompt, _ = mapdl_context

        response = llm_client.chat.completions.create(
            model="gpt-35-turbo",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": self.query},
            ],
            temperature=0.7,
            max_tokens=2000,
        )

        response_text = response.choices[0].message.content
        if not response_text or not response_text.strip():
            raise ValueError("LLM returned an empty response")

        self.code = response_text
        if Exchange is not None:
            self.exchange = Exchange(self.query, response_text)

        logger.info(f"LLM generated code:\n{self.code}")
        return response_text

    def extract_code(self) -> None:
        """Extract executable Python code from LLM response."""
        try:
            self.code = extract_executable_code(self.code)
            logger.debug(f"Extracted code:\n{self.code}")
        except ValueError as e:
            logger.error(f"Failed to extract code: {e}")
            raise

    def adapt_code(self) -> None:
        """Adapt extracted code for safe test execution.

        Removes imports, launch statements, and cleanup that should not run
        in the test environment (we provide our own MAPDL instance).
        """
        self.adapted_code = adapt_code_for_execution(self.code)
        logger.debug(f"Adapted code:\n{self.adapted_code}")

    def execute_code(self, mapdl: Any) -> None:
        """Execute the generated code against a MAPDL instance.

        Parameters
        ----------
        mapdl
            The MAPDL instance (real or mock) to execute code against

        Notes
        -----
        The `mapdl` variable is made available in the execution context.
        If execution fails, sets self.succeed = False and stores the error.
        """
        try:
            exec_globals = {"mapdl": mapdl}
            exec(self.adapted_code, exec_globals)
            self.succeed = True
            logger.info("Code executed successfully")
        except Exception as e:
            self.succeed = False
            self._error = e
            logger.error(f"Code execution failed: {e}", exc_info=True)

    # ==================== Validation Tests ====================

    @pytest.mark.llm
    def test_code_execution_succeeds(self) -> None:
        """Test that generated code executes without errors."""
        if self.succeed is None:
            pytest.skip("Code was not executed (fixture may have skipped)")

        if not self.succeed:
            error_msg = "Generated code failed to execute\n"
            error_msg += f"Error: {self._error}\n"
            error_msg += f"Code:\n{self.adapted_code}"
            raise AssertionError(error_msg) from self._error

    @pytest.mark.parametrize(
        "entity",
        ["nodes", "elements", "keypoints", "lines", "areas", "volumes"],
    )
    @pytest.mark.llm
    def test_entity_count(self, mapdl: Any, entity: str) -> None:
        """Test that the expected number of entities were created.

        Parameters
        ----------
        mapdl
            The MAPDL instance (after code execution)
        entity : str
            The entity type to check (nodes, elements, keypoints, etc.)
        """
        expected_count = getattr(self, f"num_{entity}", None)

        if expected_count is None:
            pytest.skip(f"No expected count specified for {entity}")

        if self.succeed is not True:
            pytest.skip("Code execution failed, skipping entity validation")

        # Map entity names to MAPDL attributes
        attr_map = {
            "nodes": ("mesh", "n_node"),
            "elements": ("mesh", "n_elem"),
            "keypoints": ("geometry", "n_keypoint"),
            "lines": ("geometry", "n_line"),
            "areas": ("geometry", "n_area"),
            "volumes": ("geometry", "n_volu"),
        }

        if entity not in attr_map:
            pytest.skip(f"Unknown entity type: {entity}")

        obj_name, attr_name = attr_map[entity]
        obj = getattr(mapdl, obj_name)
        actual_count = getattr(obj, attr_name)

        assert actual_count == expected_count, (
            f"Expected {expected_count} {entity}, but got {actual_count}"
        )

    @pytest.mark.llm
    def test_command_usage(self) -> None:
        """Test that expected MAPDL commands are used in generated code."""
        if not self.commands:
            pytest.skip("No commands specified for validation")

        for cmd in self.commands:
            method_name = f"mapdl.{cmd}"
            assert method_name in self.code, f"Expected command '{cmd}' not found in generated code"

    @pytest.mark.llm
    def test_response_contains_words(self) -> None:
        """Test that expected words appear in the LLM response."""
        if not self.words:
            pytest.skip("No words specified for validation")

        if ContainsWord is None:
            pytest.skip("genai-test library not available for word validation")

        if self.exchange is None:
            pytest.skip("No exchange captured (genai-test not available)")

        for word in self.words:
            validator = ContainsWord(word, case_sensitive=False)
            assert validator.evaluate(self.exchange), (
                f"Expected word '{word}' not found in LLM response"
            )

    @pytest.mark.llm
    def test_parameters(self, mapdl: Any) -> None:
        """Test that MAPDL parameters match expected values.

        Parameters
        ----------
        mapdl
            The MAPDL instance after code execution
        """
        if not self.parameters:
            pytest.skip("No parameters specified for validation")

        if self.succeed is not True:
            pytest.skip("Code execution failed, skipping parameter validation")

        for param_name, expected_value in self.parameters.items():
            actual_value = mapdl.parameters.get(param_name)
            assert actual_value == expected_value, (
                f"Parameter '{param_name}': expected {expected_value}, got {actual_value}"
            )

    @pytest.mark.llm
    def test_custom_functions(self, mapdl: Any) -> None:
        """Run custom validation functions.

        Parameters
        ----------
        mapdl
            The MAPDL instance after code execution
        """
        if not self.functions:
            pytest.skip("No custom validation functions specified")

        if self.succeed is not True:
            pytest.skip("Code execution failed, skipping custom validation")

        for func in self.functions:
            try:
                func(mapdl)
            except AssertionError as e:
                raise AssertionError(f"Custom validation function failed: {e}") from e
